### ISSUE TITLE
TypeError: compiler.plugin is not a function

### ISSUE THREAD

**Issue by LifeIsStrange** [jaywcjlove/directory-trees-webpack-plugin#1]
No idea why, on a Vue/TS project 
@jaywcjlove

``` Typescript
TypeError: compiler.plugin is not a function
    at DirectoryTreePlugin.apply (/home/stephane/dev/freelance/JardinerieApp/jardinerieApp/node_modules/directory-trees-webpack-plugin/src/index.js:88:18)
    at createCompiler (/home/stephane/dev/freelance/JardinerieApp/jardinerieApp/node_modules/webpack/lib/webpack.js:73:12)
    at create (/home/stephane/dev/freelance/JardinerieApp/jardinerieApp/node_modules/webpack/lib/webpack.js:134:16)
    at webpack (/home/stephane/dev/freelance/JardinerieApp/jardinerieApp/node_modules/webpack/lib/webpack.js:158:32)
    at f (/home/stephane/dev/freelance/JardinerieApp/jardinerieApp/node_modules/webpack/lib/index.js:58:16)
    at serve (/home/stephane/dev/freelance/JardinerieApp/jardinerieApp/node_modules/@vue/cli-service/lib/commands/serve.js:174:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

**Comment by LifeIsStrange** [comment]
oh npm list webpack says that my version of Vue CLI is using webpack 5, making this plugin incompatible...
